disabled_rules: # Default Rules에서 비활성화할 규칙
    
# 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
- trailing_whitespace
    
# 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
- force_cast
    
# 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
- force_unwrapping

opt_in_rules:
# .count==0 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_count.html
- empty_count
  
# 빈 String 문자열과 비교하는 것 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_string.html
- empty_string

excluded: # SwiftLint 검사에서 제외할 파일 경로
- today-photo/today_photoApp.swift

#- 바이너리 규칙 -#

### warning으로 처리할 지 error로 처리할 지 그 레벨을 설정할 수 있습니다.
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

#- warning, error 모두 있는 규칙 -#

### 한 줄로는 warning의 수준만 설정할 수 있습니다.
line_length: 200    # implicitly

### 배열을 사용해 warning과 error의 수준을 모두 설정할 수 있습니다.
type_body_length:
  - 300 # warning, implicitly
  - 400 # error, implicitly

file_length:
  warning: 500    # explicitly
  error: 1200    # explicitly
  
#- 네이밍 규칙 -#

### min_length 및 max_length에 대한 warning/error를 설정할 수 있습니다.
### 규칙에 제외되는 특수한 이름도 지정할 수 있습니다.
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
